### ISSUE TITLE
Добавить хранение информации об участниках стрима

### ISSUE THREAD

**Issue by pingvin1308** [cleannetcode/Lvis#4]
Это необходимо для реализации будущей фичи в апи - (Возможность добавлять новых участников занятий).

Примерный алгоритм работы такой:
1) запускается стрим - бот подключается к нему, инициализирует список участников стрима и начинает читать сообщения
2) пользователь пишет сообщение - бот разбирается сообщение. Если участник пишет первый раз (иначе говоря данный участник не был добавлен в коллекцию участников), то бот добавляет его в коллекцию. Иначе данный участник уже писал сообщения и он уже добавлен в список участников.

В будущем бот будет периодически слать запросы в апи, с целью обновить список участников и сохранить их в базе.
Данные участника можно будет потом использовать для сбора статистики и во время привязки аккаунта

**Comment by pingvin1308** [comment]
Данные о пользователе, которые нужно будет сохранять.
- channelId - так как это что то вроде уникального идентификатора юзера
- displayName - никнейм юзера (или название канала)
- profileImageUrl - опционально, но в целом было бы прикольно иметь возможность подгрузить аватарки. Все такие по авам иногда проще ориентироваться. Хотя на данном этапе наверное это не так важно.

**Comment by trulander** [comment]
Я попробую)).
